# version: '3.8'

# services:
#   mysql:
#     image: amd64/mysql:5.7.36
#     container_name: mysql_railwaydemo
#     platform: linux/amd64
#     environment:
#       MYSQL_ROOT_HOST: '%'
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "3390:3306"
#     restart: unless-stopped

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ourgroup.railway.model.dao
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/railway?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
